name: Build ASP.NET Core App

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check .NET Version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Publish application
      run: dotnet publish --configuration Release -o publish
