name: Build ASP.NET Core App

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check .NET Version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Publish application
      run: dotnet publish --configuration Release -o publish


    - name: Deploy to IIS
      shell: powershell
      run: |

        Import-Module WebAdministration

        $iisPath = "C:\inetpub\wwwroot\ToDo API"
        $appPool = "ToDo Api-Pool"

        Write-Host "Stopping IIS App Pool..."

        Stop-WebAppPool -Name $appPool


        Write-Host "Cleaning old deployment files..."

        Remove-Item "$iisPath\*" -Recurse -Force


        Write-Host "Copying new publish files..."

        Copy-Item ".\publish\*" $iisPath -Recurse -Force


        Write-Host "Starting IIS App Pool..."

        Start-WebAppPool -Name $appPool


        Write-Host "Deployment completed successfully"
